# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Myj7CQKq115LDYR4XZItASxrHWEiSJVb
"""

# 🚩 2️⃣ 새로 마운트
from google.colab import drive
drive.mount('/content/drive')

# ============================================
# 5-Class TCN — Cube.AI-friendly (60채널: RAW30 + FEATURE30) + Grid Search
# - 입력: (L=128, C=60)
#   = 5 IMUs × (ax,ay,az,gx,gy,gz, a_mag,g_mag,pitch,roll,jerk_a_mag,yaw_int)
# - 전처리: 선형 리샘플 → 채널별 z-score(μ/σ 저장)
# - 모델: Conv1D+BN+ReLU + Residual TCN blocks → GAP1D → Dense(softmax, 5)
# - 그리드 서치: ch, k, p, use_dilation 조합 탐색
# - 출력:
#   - final_export_cubeai_60ch_best.h5
#   - tcn_norm_stats.json (라벨 정보 포함)
# ============================================

from sklearn.utils.class_weight import compute_class_weight
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os, json
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# ---------- 경로/설정 ----------
BASE = "/content/drive/MyDrive/imu_data"

# ★ feature 붙인 CSV 사용 (add_c_compatible_features 돌린 결과)
CSV_PATHS = [
    f"{BASE}/imu_label_0_ALL_feat.csv",
    f"{BASE}/imu_label_1_ALL_feat.csv",
    f"{BASE}/imu_label_2_ALL_feat.csv",
    f"{BASE}/imu_label_3_ALL_feat.csv",
    f"{BASE}/imu_label_4_ALL_feat.csv",
]

L_TARGET = 128
NUM_CLASSES = 5  # 5 클래스

# ---------- 채널 정의 (보드 C코드 tmp_ext 순서와 동일) ----------
RAW_AXES   = ["ax", "ay", "az", "gx", "gy", "gz"]
FEAT_AXES  = ["a_mag", "g_mag", "pitch", "roll", "jerk_a_mag", "yaw_int"]

RAW_CHANNELS  = [f"IMU{k}_{a}" for k in range(1, 6) for a in RAW_AXES]   # 5×6 = 30
FEAT_CHANNELS = [f"IMU{k}_{a}" for k in range(1, 6) for a in FEAT_AXES]  # 5×6 = 30

# ★ 최종 순서: RAW 30 → FEATURE 30 (C 코드 tmp_ext와 꼭 맞춰야 함)
CHANNELS = RAW_CHANNELS + FEAT_CHANNELS    # 길이 60

# ---------- 유틸 ----------
def _pick_cols(df: pd.DataFrame) -> pd.DataFrame:
    """
    - *_tick, Timestep 제거
    - CHANNELS(60개) + move + label만 남겨서 순서 정렬
    """
    # 1) tick, timestep 열 제거
    df = df[[c for c in df.columns
             if "_tick" not in c.lower()
             and c.lower() != "timestep"]]

    # 2) 소문자 매핑 (대소문자 섞여 있어도 찾게)
    low = {c.lower(): c for c in df.columns}

    # 3) move/label 이름 표준화
    if "move" not in df.columns:
        mkey = next((k for k in low if k == "move"), None)
        if mkey is None:
            raise ValueError("move 컬럼 필요")
        df.rename(columns={low[mkey]: "move"}, inplace=True)

    if "label" not in df.columns:
        lkey = next((k for k in low if k == "label"), None)
        if lkey is None:
            raise ValueError("label 컬럼 필요")
        df.rename(columns={low[lkey]: "label"}, inplace=True)

    # rename 이후 다시 low 갱신
    low = {c.lower(): c for c in df.columns}

    # 4) 우리가 쓰는 60채널 순서대로 실제 컬럼명 매핑
    cols = []
    for c in CHANNELS:
        key = c.lower()
        if key not in low:
            raise ValueError(f"필수 컬럼 누락: {c}")
        cols.append(low[key])

    # 최종: [60채널] + move + label
    return df[cols + ["move", "label"]]


def _resample_to_L(x_T_C: np.ndarray, L: int = 128) -> np.ndarray:
    """
    x: [T, C] → 선형 보간으로 [L, C]
    """
    T, C = x_T_C.shape
    if T < 2:
        # 샘플이 1개면 그대로 반복
        return np.repeat(x_T_C, L, axis=0)

    t_src = np.linspace(0.0, 1.0, num=T, dtype=np.float32)
    t_dst = np.linspace(0.0, 1.0, num=L, dtype=np.float32)
    out = np.empty((L, C), dtype=np.float32)

    for c in range(C):
        out[:, c] = np.interp(t_dst, t_src, x_T_C[:, c])

    return out


def build_dataset(paths):
    X_list, y_list = [], []
    for p in paths:
        if not os.path.exists(p):
            print(f"[WARN] not found: {p}")
            continue

        df = pd.read_csv(p)
        df = _pick_cols(df)   # → 60채널 + move + label

        # move 단위로 잘라서 한 동작 = 한 샘플
        for mv, g in df.groupby("move"):
            x = g[CHANNELS].astype(np.float32).values   # [T, 60]
            x = _resample_to_L(x, L=L_TARGET)           # [128, 60]
            X_list.append(x)

            # 무브 내 라벨 혼재 시 다수결(평균 반올림)
            y_list.append(int(np.round(g["label"].astype(int).mean())))

    X = np.stack(X_list, axis=0)            # [N, 128, 60]
    y = np.array(y_list, dtype=np.int32)    # [N]
    return X, y


# ---------- 데이터 로드 ----------
X_all, y_all = build_dataset(CSV_PATHS)
print("Original dataset:", X_all.shape, "class dist:", np.bincount(y_all))

N, L_used, C = X_all.shape
assert L_used == L_TARGET, f"L mismatch: {L_used} vs {L_TARGET}"
assert C == len(CHANNELS) == 60, f"C mismatch: {C}"

# ---------- train / val / test split ----------
rng = np.random.RandomState(42)
idx = np.arange(N)
rng.shuffle(idx)

tr_end = int(N * 0.6)   # 60% train
va_end = int(N * 0.8)   # 20% val (60~80%)
tr_idx = idx[:tr_end]
va_idx = idx[tr_end:va_end]
te_idx = idx[va_end:]   # 나머지 20% test

# ★ 실제 데이터 분할
Xtr_raw = X_all[tr_idx]
Xva_raw = X_all[va_idx]
Xte_raw = X_all[te_idx]

ytr = y_all[tr_idx]
yva = y_all[va_idx]
yte = y_all[te_idx]

print("Train shape:", Xtr_raw.shape, "class dist:", np.bincount(ytr))
print("Val   shape:", Xva_raw.shape, "class dist:", np.bincount(yva))
print("Test  shape:", Xte_raw.shape, "class dist:", np.bincount(yte))

# ---------- 정규화 (train 기준 μ/σ, 채널별) ----------
flat_tr = Xtr_raw.reshape(-1, Xtr_raw.shape[-1])  # [Ntr*L, C]
mu = flat_tr.mean(axis=0)
sigma = flat_tr.std(axis=0)
sigma[sigma < 1e-6] = 1.0   # 0 division 방지

Xtr = (Xtr_raw - mu) / sigma
Xva = (Xva_raw - mu) / sigma
Xte = (Xte_raw - mu) / sigma

# from_log 등 이후 디버깅용 전체 정규화 버전
X_all_norm = (X_all.astype(np.float32) - mu) / sigma

# ---------- μ/σ + 라벨 정보 JSON 저장 (C 코드에서 사용) ----------
stats_path = f"{BASE}/tcn_norm_stats.json"
norm_stats = {
    "L": int(L_TARGET),
    "channels": CHANNELS,                 # 길이 60
    "mu": mu.tolist(),                    # 60개
    "sigma": sigma.tolist(),              # 60개
    "label_map": {str(i): int(i) for i in range(NUM_CLASSES)}
}
with open(stats_path, "w", encoding="utf-8") as f:
    json.dump(norm_stats, f, indent=2, ensure_ascii=False)

print("Saved norm stats to:", stats_path)

# ---------- 클래스 불균형 보정 (class_weight) ----------
classes = np.unique(ytr)
class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=ytr
)
class_weight = {int(c): float(w) for c, w in zip(classes, class_weights_arr)}
print("class_weight:", class_weight)

# ---------- 🔍 디버그: 라벨별로 최대 5개씩 CSV 저장 (MATLAB 시각화용) ----------
dbg_dir = f"{BASE}/dbg_inputs_per_label_60ch"
os.makedirs(dbg_dir, exist_ok=True)

max_per_label = 5  # 라벨당 최대 몇 개 저장할지

for cls in range(NUM_CLASSES):   # 0,1,2,3,4
    idx_cls = np.where(y_all == cls)[0]
    if len(idx_cls) == 0:
        print(f"[WARN] label {cls} 샘플이 없습니다.")
        continue

    rng = np.random.RandomState(1234 + cls)
    rng.shuffle(idx_cls)
    sel_idx = idx_cls[:max_per_label]

    for j, idx0 in enumerate(sel_idx):
        x_one = X_all_norm[idx0]   # (128, 60)

        df_dbg = pd.DataFrame(x_one, columns=CHANNELS)
        df_dbg.insert(0, "Timestep", np.arange(L_TARGET, dtype=np.int32))  # 0~127
        df_dbg["move"] = np.ones(L_TARGET, dtype=np.int32) * (j + 1)
        df_dbg["label"] = np.ones(L_TARGET, dtype=np.int32) * cls

        out_path = f"{dbg_dir}/label{cls}_sample{j}_idx{idx0}.csv"
        df_dbg.to_csv(out_path, index=False, encoding="utf-8-sig")
        print(f"saved: {out_path}")

# ---------- TCN 모델 (60채널 입력) ----------
def tcn_block(x, ch, k, dilation=1, p=0.3, name_prefix="tcn"):
    h = layers.Conv1D(ch, k, padding="same",
                      dilation_rate=dilation,
                      use_bias=False,
                      name=f"{name_prefix}_conv1_d{dilation}")(x)
    h = layers.BatchNormalization(name=f"{name_prefix}_bn1_d{dilation}")(h)
    h = layers.ReLU(name=f"{name_prefix}_relu1_d{dilation}")(h)
    if p > 0:
        h = layers.Dropout(p, name=f"{name_prefix}_drop1_d{dilation}")(h)

    h = layers.Conv1D(ch, k, padding="same",
                      dilation_rate=dilation,
                      use_bias=False,
                      name=f"{name_prefix}_conv2_d{dilation}")(x)
    h = layers.BatchNormalization(name=f"{name_prefix}_bn2_d{dilation}")(h)

    x = layers.Add(name=f"{name_prefix}_add_d{dilation}")([x, h])
    x = layers.ReLU(name=f"{name_prefix}_out_relu_d{dilation}")(x)
    return x


def tcn_model(input_shape,
              num_classes=5,
              ch=48,
              k=5,
              p=0.2,
              use_dilation=True):
    inp = keras.Input(shape=input_shape, name="imu")  # [L, C]

    # stem
    x = layers.Conv1D(ch, k, padding="same", use_bias=False, name="stem_conv")(inp)
    x = layers.BatchNormalization(name="stem_bn")(x)
    x = layers.ReLU(name="stem_relu")(x)
    if p > 0:
        x = layers.Dropout(p, name="stem_drop")(x)

    # TCN blocks
    d_list = [1, 2, 4] if use_dilation else [1, 1, 1]
    for i, d in enumerate(d_list):
        x = tcn_block(
            x, ch=ch, k=k, dilation=d, p=p,
            name_prefix=f"tcn_block{i+1}"
        )

    # head
    x = layers.GlobalAveragePooling1D(name="gap")(x)
    out = layers.Dense(num_classes, activation="softmax", name="pred")(x)

    return keras.Model(inp, out, name="tcn_squat_5cls_60ch")

# ---------- Grid Search 설정 ----------
GRID_CH = [48, 64]           # Conv 채널 수 후보
GRID_K  = [3, 5]             # 커널 크기 후보
GRID_P  = [0.1, 0.2]         # Dropout 후보
GRID_D  = [True, False]      # dilation 사용 여부

EPOCHS_PER_TRIAL = 40        # 각 조합당 최대 epoch
BATCH_SIZE = 32

def train_one_config(ch, k, p, use_dilation):
    print(f"\n===== [GRID] ch={ch}, k={k}, p={p}, use_dilation={use_dilation} =====")

    model = tcn_model(
        (L_TARGET, C),
        NUM_CLASSES,
        ch=ch,
        k=k,
        p=p,
        use_dilation=use_dilation
    )

    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    # 콜백은 매 trial마다 새로 생성
    cbs = [
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_accuracy",
            factor=0.5,
            patience=4,
            verbose=1,
            min_lr=1e-5
        ),
        keras.callbacks.EarlyStopping(
            monitor="val_accuracy",
            patience=8,
            restore_best_weights=True,
            verbose=1
        )
    ]

    history = model.fit(
        Xtr, ytr,
        validation_data=(Xva, yva),
        epochs=EPOCHS_PER_TRIAL,
        batch_size=BATCH_SIZE,
        verbose=2,
        class_weight=class_weight,
        callbacks=cbs
    )

    val_acc_hist = history.history["val_accuracy"]
    best_val_acc = float(np.max(val_acc_hist))
    best_epoch = int(np.argmax(val_acc_hist))

    print(f"[GRID] best val_acc={best_val_acc:.4f} at epoch {best_epoch+1}")

    return model, best_val_acc, best_epoch, history

# ---------- 실제 그리드 서치 루프 ----------
results = []
best_model = None
best_score = -1.0
best_cfg = None

trial_id = 0

for ch in GRID_CH:
    for k in GRID_K:
        for p in GRID_P:
            for use_dilation in GRID_D:
                trial_id += 1
                print(f"\n########## Trial {trial_id} ##########")
                print(f"config: ch={ch}, k={k}, p={p}, use_dilation={use_dilation}")

                model, val_acc, best_epoch, history = train_one_config(ch, k, p, use_dilation)

                # 결과 기록
                results.append({
                    "trial": trial_id,
                    "ch": ch,
                    "k": k,
                    "p": p,
                    "use_dilation": use_dilation,
                    "best_val_acc": val_acc,
                    "best_epoch": best_epoch + 1
                })

                # 최고 성능 모델 갱신
                if val_acc > best_score:
                    best_score = val_acc
                    best_cfg = {
                        "ch": ch,
                        "k": k,
                        "p": p,
                        "use_dilation": use_dilation
                    }
                    best_model = model
                    print(f"🔺 New BEST config! val_acc={best_score:.4f}, cfg={best_cfg}")

# 그리드 결과 한 번에 보기
results_df = pd.DataFrame(results).sort_values("best_val_acc", ascending=False)
print("\n===== Grid Search Results (Top) =====")
print(results_df.head(10))

# ---------- 베스트 모델 테스트셋 평가 ----------
if best_model is None:
    raise RuntimeError("그리드 서치에서 best_model이 설정되지 않았습니다.")

test_loss, test_acc = best_model.evaluate(Xte, yte, batch_size=BATCH_SIZE, verbose=0)
print(f"\n✅ BEST CONFIG: {best_cfg}")
print(f"✅ Test accuracy = {test_acc:.4f}, loss = {test_loss:.4f}")

# ---------- 내보내기 (Cube.AI용 .h5) ----------
save_path = f"{BASE}/final_export_cubeai_60ch_best.h5"
best_model.save(save_path)
print("Saved BEST model to:", save_path)

# ---------- label 4 디버그 (BEST 모델 기준) ----------
idx4 = np.where(y_all == 4)[0]
if len(idx4) > 0:
    X4 = X_all_norm[idx4]

    proba4 = best_model.predict(X4, batch_size=32, verbose=0)
    pred4  = np.argmax(proba4, axis=1)

    print("label4 count:", len(idx4))
    print("label4 → predicted class distribution:", np.bincount(pred4, minlength=5))
else:
    print("⚠ label 4 샘플이 없습니다.")

import numpy as np
import pandas as pd
from tensorflow import keras

BASE = "/content/drive/MyDrive/imu_data"  # 네가 학습에 쓰던 경로
CSV_PATH = f"{BASE}/imu_from_log.csv"     # 전처리 끝난 CSV 경로

# 학습 때 썼던 채널 순서랑 똑같이
axes = ["ax","ay","az","gx","gy","gz"]
CHANNELS = [f"IMU{k}_{a}" for k in range(1,6) for a in axes]  # 30개
L = 128
MODEL_PATH = f"{BASE}/final_export_cubeai.h5"

model = keras.models.load_model(MODEL_PATH, compile=False)
print("loaded model:", MODEL_PATH)

df = pd.read_csv(CSV_PATH)
x = df[CHANNELS].astype(np.float32).values      # (128, 30)
x_in = np.expand_dims(x, axis=0)                # (1, 128, 30)

proba = model.predict(x_in)[0]
print("proba =", proba, "  sum =", proba.sum())
print("pred class =", np.argmax(proba))



!mkdir -p /content/drive/MyDrive/imu_model
!cp /content/export_st/tcn_export_fp32.h5 /content/drive/MyDrive/imu_model/
!cp /content/export_st/imu_norm_params.h /content/drive/MyDrive/imu_model/

# === Generate C preprocessing files from stats JSON (60채널 대응 버전) ===
import json, os

BASE = "/content/drive/MyDrive/imu_data"   # 학습에 사용한 폴더와 동일하게

# --- 1) JSON 읽기 ---
with open(f"{BASE}/tcn_norm_stats.json", "r", encoding="utf-8") as f:
    stats = json.load(f)

# JSON 안에 들어있는 값 사용
L = int(stats.get("L", 128))     # 기본값 128
mu = stats["mu"]
sigma = stats["sigma"]

C = len(mu)                      # 채널 수 = mu 길이 (지금은 60이어야 함)
assert len(sigma) == C, "mu/sigma 길이가 다릅니다!"
if "channels" in stats:
    assert len(stats["channels"]) == C, "channels 길이와 mu 길이가 다릅니다!"

print(f"[INFO] L={L}, C={C}, len(mu)={len(mu)}, len(sigma)={len(sigma)}")

def fmt(arr):
    lines = []
    for x in arr:
        lines.append(f"{float(x):.6f}f")
    # 보기 좋게 줄바꿈
    return ",\n  ".join(lines)

# --- 2) 헤더 파일 내용 ---
h = f"""#ifndef CUBEAI_PREPROCESS_H
#define CUBEAI_PREPROCESS_H
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

// --- TCN 입력 크기 (JSON에서 읽어옴) ---
#define TCN_L {L}
#define TCN_C {C}

// 선형 리샘플: src [src_len, C] → dst [L, C]
void tcn_linear_resample(const float* src, int src_len, int C, float* dst, int L);

// 채널별 z-score 정규화 (μ/σ)
void tcn_normalize_inplace(float* x, int L, int C);

// 디버깅용 getter
const float* tcn_get_mu(void);
const float* tcn_get_sigma(void);

#ifdef __cplusplus
}}
#endif
#endif // CUBEAI_PREPROCESS_H
"""

# --- 3) C 파일 내용 ---
c = f"""#include "cubeai_preprocess.h"
#include <math.h>
#include <stddef.h>

// 채널별 평균/표준편차 (길이 TCN_C = {C})
static const float kMu[TCN_C] = {{
  {fmt(mu)}
}};

static const float kSigma[TCN_C] = {{
  {fmt(sigma)}
}};

// src: [src_len, C] row-major → dst: [L, C]
void tcn_linear_resample(const float* src, int src_len, int C, float* dst, int L) {{
    if (!src || !dst || src_len <= 0 || L <= 0 || C <= 0) return;

    for (int i = 0; i < L; ++i) {{
        float pos = (float)(src_len - 1) * (float)i / (float)(L - 1);
        int i0 = (int)pos;
        int i1 = i0 + 1;
        if (i0 < 0) i0 = 0;
        if (i1 >= src_len) i1 = src_len - 1;
        float t = pos - (float)i0;

        const float* s0 = src + (size_t)i0 * C;
        const float* s1 = src + (size_t)i1 * C;
        float* d = dst + (size_t)i * C;

        for (int c = 0; c < C; ++c) {{
            d[c] = s0[c] * (1.0f - t) + s1[c] * t;
        }}
    }}
}}

// x: [L, C] row-major
void tcn_normalize_inplace(float* x, int L, int C) {{
    if (!x || L <= 0 || C <= 0) return;

    const float eps = 1e-6f;
    for (int i = 0; i < L; ++i) {{
        float* row = x + (size_t)i * C;
        for (int c = 0; c < C; ++c) {{
            float s = kSigma[c];
            if (s < eps) s = 1.0f;
            row[c] = (row[c] - kMu[c]) / s;
        }}
    }}
}}

const float* tcn_get_mu(void)    {{ return kMu;    }}
const float* tcn_get_sigma(void) {{ return kSigma; }}
"""

# --- 4) 파일로 저장 ---
with open(f"{BASE}/cubeai_preprocess.h", "w", encoding="utf-8") as f:
    f.write(h)
with open(f"{BASE}/cubeai_preprocess.c", "w", encoding="utf-8") as f:
    f.write(c)

print("Created:")
print(f" - {BASE}/cubeai_preprocess.h")
print(f" - {BASE}/cubeai_preprocess.c")